In [2]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-1.2121e-27,  1.3368e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
x.shape

torch.Size([5, 3])

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3469, 0.5843, 0.4491],
        [0.8106, 0.5793, 0.3421],
        [0.6939, 0.5143, 0.7459],
        [0.1423, 0.5377, 0.8063],
        [0.5493, 0.1960, 0.3035]])


In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = torch.ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.0773, 0.8768, 0.4761],
        [0.9941, 0.9972, 0.8554],
        [0.1780, 0.0294, 0.4503],
        [0.6053, 0.2714, 0.1760],
        [0.2303, 0.7694, 0.4464]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
print(x.shape)

torch.Size([5, 3])


In [23]:
x = torch.Tensor(12)
print(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [24]:
x = torch.tensor([12, 34, 56])
print(x)

tensor([12, 34, 56])


In [26]:
x = torch.eye(12)
print(x)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


In [32]:
x = torch.arange(0, 13, 2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12])


In [38]:
x = torch.linspace(0, 15, 4)
print(x)

tensor([ 0.,  5., 10., 15.])


In [51]:
x = torch.rand(12)
print(x)

tensor([0.4305, 0.4877, 0.0067, 0.0049, 0.3661, 0.3646, 0.7424, 0.6442, 0.1729,
        0.1714, 0.4435, 0.5804])


In [52]:
x = torch.normal(x)
print(x)

tensor([-1.7323,  1.3306, -0.9218, -2.9884,  0.8397,  1.2467,  0.6321,  1.3510,
        -0.5674, -0.9320,  0.7527,  0.3641])


In [46]:
x = torch.randperm(12)
print(x)

tensor([ 0,  4,  5,  7,  8,  6,  3,  2,  1,  9, 11, 10])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3322, 0.7212, 0.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.3902, 0.8592],
        [0.7305, 0.4557, 0.6355],
        [0.9103, 0.5325, 0.4859]])


In [11]:
y = torch.rand(5,3)
print(y)

tensor([[0.7816, 0.8300, 0.9214],
        [0.3921, 0.4981, 0.7007],
        [0.9556, 0.5980, 0.2907],
        [0.7552, 0.7242, 0.2252],
        [0.0384, 0.7763, 0.1832]])


In [12]:
print(x + y)

tensor([[1.1137, 1.5513, 1.4921],
        [1.0776, 1.4958, 1.3790],
        [1.9105, 0.9882, 1.1498],
        [1.4857, 1.1800, 0.8607],
        [0.9487, 1.3088, 0.6691]])


In [13]:
print(torch.add(x, y))

tensor([[1.1137, 1.5513, 1.4921],
        [1.0776, 1.4958, 1.3790],
        [1.9105, 0.9882, 1.1498],
        [1.4857, 1.1800, 0.8607],
        [0.9487, 1.3088, 0.6691]])


In [14]:
result = torch.empty(5,3)
print(result)

tensor([[-1.3018e-18,  1.3523e-42,  0.0000e+00],
        [ 1.9034e+00, -2.0000e+00,  1.8249e+00],
        [-1.0842e-19,  1.8971e+00,  0.0000e+00],
        [ 1.9051e+00, -1.0842e-19,  1.8676e+00],
        [-0.0000e+00,  1.9818e+00,  2.0000e+00]])


In [15]:
torch.add(x, y, out=result)
print(result)

tensor([[1.1137, 1.5513, 1.4921],
        [1.0776, 1.4958, 1.3790],
        [1.9105, 0.9882, 1.1498],
        [1.4857, 1.1800, 0.8607],
        [0.9487, 1.3088, 0.6691]])


In [17]:
y.add(x)
print(y)

tensor([[1.1137, 1.5513, 1.4921],
        [1.0776, 1.4958, 1.3790],
        [1.9105, 0.9882, 1.1498],
        [1.4857, 1.1800, 0.8607],
        [0.9487, 1.3088, 0.6691]])


In [16]:
y.add_(x)
print(y)

tensor([[1.1137, 1.5513, 1.4921],
        [1.0776, 1.4958, 1.3790],
        [1.9105, 0.9882, 1.1498],
        [1.4857, 1.1800, 0.8607],
        [0.9487, 1.3088, 0.6691]])


In [18]:
y = x[0, :]
print(y)

tensor([0.3322, 0.7212, 0.5707])


In [19]:
y += 1
print(y)

tensor([1.3322, 1.7212, 1.5707])


In [20]:
print(x[0, :])

tensor([1.3322, 1.7212, 1.5707])


In [28]:
print(x)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.3902, 0.8592],
        [0.7305, 0.4557, 0.6355],
        [0.9103, 0.5325, 0.4859]])


In [25]:
idx = torch.tensor([0, 1])
result = torch.index_select(x, dim = 0, index=idx)
print(result)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783]])


In [26]:
idx = torch.tensor([0, 1])
result = torch.index_select(x, dim = 1, index=idx)
print(result)

tensor([[1.3322, 1.7212],
        [0.6856, 0.9976],
        [0.9549, 0.3902],
        [0.7305, 0.4557],
        [0.9103, 0.5325]])


In [29]:
idx = torch.tensor([True, False, True])
result = torch.masked_select(x, mask=idx)
print(result)

tensor([1.3322, 1.5707, 0.6856, 0.6783, 0.9549, 0.8592, 0.7305, 0.6355, 0.9103,
        0.4859])


In [32]:
idx = torch.tensor([[True, False, True],
                    [True, False, False],
                    [False, True, True],
                    [False, False, True],
                    [True, True, True],
                    ])
result = torch.masked_select(x, mask=idx)
print(result)

tensor([1.3322, 1.5707, 0.6856, 0.3902, 0.8592, 0.6355, 0.9103, 0.5325, 0.4859])


In [33]:
mask = x > 1
positive = torch.masked_select(x, mask)
print("大于1的元素:", positive)

大于1的元素: tensor([1.3322, 1.7212, 1.5707])


In [34]:
mask = (x >= 0.5) & (x <= 0.8)
result = torch.masked_select(x, mask)
print(result)

tensor([0.6856, 0.6783, 0.7305, 0.6355, 0.5325])


In [46]:
print(x)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.3902, 0.8592],
        [0.7305, 0.4557, 0.6355],
        [0.9103, 0.5325, 0.4859]])


In [68]:
result = torch.where(x < 0.5, torch.tensor(0.0), x)
print(result)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.0000, 0.8592],
        [0.7305, 0.0000, 0.6355],
        [0.9103, 0.5325, 0.0000]])


In [67]:
idx = torch.nonzero(result)
print(idx)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 2],
        [3, 0],
        [3, 2],
        [4, 0],
        [4, 1]])


In [72]:
mask = torch.tensor([[0, 4, 3],
                     [4, 3, 2],
                     [1, 2, 1],
                     [2, 0, 2],
                     [3, 1, 0],
                     ])
i = torch.gather(result, 0, mask)
print(i)

tensor([[1.3322, 0.5325, 0.6355],
        [0.9103, 0.0000, 0.8592],
        [0.6856, 0.0000, 0.6783],
        [0.9549, 1.7212, 0.8592],
        [0.7305, 0.9976, 1.5707]])


In [42]:
print(x)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.3902, 0.8592],
        [0.7305, 0.4557, 0.6355],
        [0.9103, 0.5325, 0.4859]])


In [73]:
y = x.view(15)
print(y)

tensor([1.3322, 1.7212, 1.5707, 0.6856, 0.9976, 0.6783, 0.9549, 0.3902, 0.8592,
        0.7305, 0.4557, 0.6355, 0.9103, 0.5325, 0.4859])


In [74]:
z = x.view(-1, 5)
print(z)

tensor([[1.3322, 1.7212, 1.5707, 0.6856, 0.9976],
        [0.6783, 0.9549, 0.3902, 0.8592, 0.7305],
        [0.4557, 0.6355, 0.9103, 0.5325, 0.4859]])


In [75]:
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [76]:
x += 1
print(x)

tensor([[2.3322, 2.7212, 2.5707],
        [1.6856, 1.9976, 1.6783],
        [1.9549, 1.3902, 1.8592],
        [1.7305, 1.4557, 1.6355],
        [1.9103, 1.5325, 1.4859]])


In [77]:
print(y)

tensor([2.3322, 2.7212, 2.5707, 1.6856, 1.9976, 1.6783, 1.9549, 1.3902, 1.8592,
        1.7305, 1.4557, 1.6355, 1.9103, 1.5325, 1.4859])


In [78]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[1.3322, 1.7212, 1.5707],
        [0.6856, 0.9976, 0.6783],
        [0.9549, 0.3902, 0.8592],
        [0.7305, 0.4557, 0.6355],
        [0.9103, 0.5325, 0.4859]])
tensor([2.3322, 2.7212, 2.5707, 1.6856, 1.9976, 1.6783, 1.9549, 1.3902, 1.8592,
        1.7305, 1.4557, 1.6355, 1.9103, 1.5325, 1.4859])


In [79]:
x = torch.rand(1)
print(x.item())

0.007751822471618652


In [83]:
x = torch.rand(4)
x = x.view(-1, 2)
print(x)

tensor([[0.9826, 0.2849],
        [0.6503, 0.5645]])


In [86]:
tr = torch.trace(x)
print(tr)

tensor(1.5471)


In [88]:
x[0,0] + x[1,1]

tensor(1.5471)

In [90]:
torch.diag(x).sum()

tensor(1.5471)

In [91]:
x.triu()

tensor([[0.9826, 0.2849],
        [0.0000, 0.5645]])

In [92]:
x.tril()

tensor([[0.9826, 0.0000],
        [0.6503, 0.5645]])

In [96]:
batch_matrices = torch.randn(3, 4, 4)  # 3个4x4矩阵
print(f"批量矩阵形状: {batch_matrices.shape}")  # torch.Size([3, 4, 4])
print(batch_matrices)
# 方法1：循环计算每个矩阵的迹
traces = torch.tensor([torch.trace(mat) for mat in batch_matrices])
print(f"迹: {traces}")
print(f"批量迹形状: {traces.shape}")  # torch.Size([3])

批量矩阵形状: torch.Size([3, 4, 4])
tensor([[[-1.2133,  1.7618,  0.1828,  0.9320],
         [-0.8143, -0.2278, -0.1329,  1.3078],
         [-0.8064,  1.4506,  0.7041,  1.4151],
         [ 0.0397,  0.8138, -1.8018,  0.4759]],

        [[ 0.0961,  0.4693, -0.9193, -1.0055],
         [ 0.3387,  0.4455, -0.0876, -1.3261],
         [ 2.6148, -2.6595, -0.2226,  0.6198],
         [-1.3550,  2.8183, -0.3405,  0.8074]],

        [[ 0.5241,  2.5887,  0.7703, -0.3866],
         [ 1.9315, -2.0834,  0.2214,  0.1127],
         [ 1.9978, -2.3880, -1.1045,  1.2486],
         [-0.1139, -0.0716,  0.2584, -0.8350]]])
迹: tensor([-0.2611,  1.1264, -3.4988])
批量迹形状: torch.Size([3])


In [97]:
# 方法2：使用爱因斯坦求和约定
traces = torch.einsum('bii->b', batch_matrices)
print(f"迹: {traces}")
print(f"批量迹形状: {traces.shape}")  # torch.Size([3])

迹: tensor([-0.2611,  1.1264, -3.4988])
批量迹形状: torch.Size([3])


In [98]:
# 从矩阵提取对角线
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
diag = torch.diag(x)
print(f"对角线: {diag}")  # tensor([1, 5, 9])

# 带偏移量的对角线
diag_offset = torch.diag(x, diagonal=1)  # 上对角线
print(f"上对角线(偏移1): {diag_offset}")  # tensor([2, 6])

diag_offset2 = torch.diag(x, diagonal=-1)  # 下对角线
print(f"下对角线(偏移-1): {diag_offset2}")  # tensor([4, 8])

# 从向量创建对角矩阵
v = torch.tensor([1, 2, 3])
diag_matrix = torch.diag(v)
print(f"对角矩阵:\n{diag_matrix}")
# tensor([[1, 0, 0],
#         [0, 2, 0],
#         [0, 0, 3]])

对角线: tensor([1, 5, 9])
上对角线(偏移1): tensor([2, 6])
下对角线(偏移-1): tensor([4, 8])
对角矩阵:
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


In [99]:
v = torch.tensor([1,2,3,4,5])
diag_matrix = torch.diag(v)
print(diag_matrix)

tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])


In [101]:
x = torch.arange(1, 17, 1)
print(x)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


In [102]:
x = x.view(4,4)
print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [103]:
upper = x.triu()
print(upper)

tensor([[ 1,  2,  3,  4],
        [ 0,  6,  7,  8],
        [ 0,  0, 11, 12],
        [ 0,  0,  0, 16]])


In [104]:
lower = x.tril()
print(lower)

tensor([[ 1,  0,  0,  0],
        [ 5,  6,  0,  0],
        [ 9, 10, 11,  0],
        [13, 14, 15, 16]])


In [105]:
upper_offset1 = x.triu(diagonal=1)
print(upper_offset1)

tensor([[ 0,  2,  3,  4],
        [ 0,  0,  7,  8],
        [ 0,  0,  0, 12],
        [ 0,  0,  0,  0]])


In [106]:
lower_offset1 = x.tril(diagonal=-1)
print(lower_offset1)

tensor([[ 0,  0,  0,  0],
        [ 5,  0,  0,  0],
        [ 9, 10,  0,  0],
        [13, 14, 15,  0]])


In [115]:
# mm: 2D 矩阵乘法
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])
C = torch.mm(A, B)
print(f"矩阵乘法结果:\n{C}")
# tensor([[19, 22],
#         [43, 50]])

# 等价于
C2 = A @ B
print(f"使用@运算符:\n{C2}")

# bmm: batch 矩阵乘法
batch_A = torch.randn(10, 3, 4)  # 10个3x4矩阵
batch_B = torch.randn(10, 4, 5)  # 10个4x5矩阵
batch_C = torch.bmm(batch_A, batch_B)
print(f"批量矩阵乘法形状: {batch_C.shape}")  # torch.Size([10, 3, 5])

# 手动实现 bmm
batch_C_manual = torch.stack([torch.mm(a, b) for a, b in zip(batch_A, batch_B)])
print(f"手动批量乘法形状: {batch_C_manual.shape}")

矩阵乘法结果:
tensor([[19, 22],
        [43, 50]])
使用@运算符:
tensor([[19, 22],
        [43, 50]])
批量矩阵乘法形状: torch.Size([10, 3, 5])
手动批量乘法形状: torch.Size([10, 3, 5])


In [117]:
C1 = A[0][0] * B[0][0] + A[0][1] * B[1][0]
print(C1)

tensor(19)


In [119]:
C2 = A[0][0] * B[0][1] + A[0][1] * B[1][1]
print(C2)

tensor(22)


In [120]:
C3 = A[1][0] * B[0][0] + A[1][1] * B[1][0]
print(C3)

tensor(43)


In [121]:
C4 = A[1][0] * B[0][1] + A[1][1] * B[1][1]
print(C4)

tensor(50)


In [123]:
# 等价于
C2 = A @ B
print(f"使用@运算符:\n{C2}")

使用@运算符:
tensor([[19, 22],
        [43, 50]])


In [130]:
# bmm: batch 矩阵乘法
batch_A = torch.randn(10, 3, 4)  # 10个3x4矩阵
print("batch_A: ", batch_A)
batch_B = torch.randn(10, 4, 5)  # 10个4x5矩阵
print("batch_B: ", batch_B)
batch_C = torch.bmm(batch_A, batch_B)
print("batch_C: ", batch_C)
print(f"批量矩阵乘法形状: {batch_C.shape}")  # torch.Size([10, 3, 5])

batch_A:  tensor([[[ 0.4444, -0.1958, -0.2495, -0.3760],
         [ 0.3474, -2.0768,  1.1954,  1.6756],
         [-2.6283,  1.3148,  0.1648,  1.4699]],

        [[ 1.3433,  1.0300, -1.1119, -0.6733],
         [ 0.4945, -1.4855, -0.2695, -1.5548],
         [ 0.6554,  0.9569,  0.0934, -1.2554]],

        [[-0.2006, -0.0822,  1.4101,  0.8970],
         [ 1.3226, -1.0176, -1.4321, -0.2162],
         [-0.7999, -0.1863, -0.8555,  1.5139]],

        [[ 0.2767, -1.8072, -0.2854,  1.0598],
         [ 0.6064, -0.4432, -0.3199,  0.3521],
         [-0.0496,  0.0574,  1.9695,  0.4563]],

        [[ 1.0785,  0.2401, -0.2928,  2.5584],
         [-1.1695,  0.0986, -2.2772, -0.8986],
         [ 1.4534,  0.8272, -2.7471, -0.3039]],

        [[ 0.2436,  0.2325, -1.4252, -1.8544],
         [ 1.6723,  0.1286,  0.9694,  1.9378],
         [-0.1826,  2.0691, -0.2714,  0.3874]],

        [[-0.1699, -1.8286, -0.2050,  0.4212],
         [ 0.5786,  0.1826, -0.4327,  0.6131],
         [-0.8544,  0.4663,  0.6378, -

In [131]:
# 手动实现 bmm
batch_C_manual = torch.stack([torch.mm(a, b) for a, b in zip(batch_A, batch_B)])
print(batch_C_manual)
print(f"手动批量乘法形状: {batch_C_manual.shape}")

tensor([[[ 0.8452,  0.4908,  0.0706, -0.8147, -0.8300],
         [ 0.6767, -0.7953,  0.2454,  0.6116, -6.2009],
         [-4.3644, -0.9591, -1.9449,  2.8298,  5.7915]],

        [[-1.9908,  1.5110,  1.3188, -1.7682,  0.7820],
         [ 1.0910, -2.4643,  1.0955,  0.3489,  2.3598],
         [ 0.4519,  1.3998,  1.1972, -0.5015, -0.4289]],

        [[ 1.6548, -1.1415, -1.9578, -0.3865, -2.3149],
         [ 1.0416,  0.0214,  1.6049,  1.4183,  2.4971],
         [ 2.9001, -1.9530,  1.1031,  1.6853, -0.1314]],

        [[-0.1275,  1.6175, -0.9393,  1.7563, -0.7083],
         [ 0.0152,  0.7304,  0.1423,  0.7473, -0.2423],
         [-2.2101,  0.9699,  0.5618,  1.1447,  0.6363]],

        [[ 0.2291,  2.6098,  4.3233, -2.7850,  1.6310],
         [-1.4656,  3.0656, -6.0907, -4.2448,  0.6832],
         [ 2.6990,  4.4693, -2.5401, -3.9334,  1.4359]],

        [[ 2.2564,  0.5476,  4.4015,  0.2745, -2.1160],
         [-3.0924, -2.2696, -2.6844, -0.2494,  2.6117],
         [-2.0960,  1.3564,  0.3403,  

In [132]:
# addmm: C = α * (A @ B) + β * C
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
C = torch.tensor([[10, 10], [10, 10]])

result = torch.addmm(C, A, B)
print(f"addmm:\n{result}")
# tensor([[29, 32],
#         [53, 60]])

# 带缩放因子
result = torch.addmm(C, A, B, alpha=0.5, beta=2)
print(f"addmm with scaling:\n{result}")

# addbmm: 批量矩阵乘法后累加
batch_A = torch.randn(3, 4, 5)   # 3个4x5矩阵
batch_B = torch.randn(3, 5, 6)   # 3个5x6矩阵
C = torch.randn(4, 6)
result = torch.addbmm(C, batch_A, batch_B)  # C + sum(A[i] @ B[i])
print(f"addbmm结果形状: {result.shape}")  # torch.Size([4, 6])

# addmv: 矩阵乘向量
M = torch.tensor([[1, 2], [3, 4]])
vec = torch.tensor([5, 6])
bias = torch.tensor([10, 10])
result = torch.addmv(bias, M, vec)
print(f"addmv: {result}")  # bias + M @ vec

# addr: 外积累加
vec1 = torch.tensor([1, 2, 3])
vec2 = torch.tensor([4, 5])
matrix = torch.zeros(3, 2)
result = torch.addr(matrix, vec1, vec2)
print(f"addr结果:\n{result}")

# baddbmm: 批量矩阵乘法后累加（带缩放）
batch_C = torch.randn(10, 3, 5)
batch_A = torch.randn(10, 3, 4)
batch_B = torch.randn(10, 4, 5)
result = torch.baddbmm(batch_C, batch_A, batch_B, alpha=0.5, beta=1)
print(f"baddbmm形状: {result.shape}")  # torch.Size([10, 3, 5])

addmm:
tensor([[29, 32],
        [53, 60]])
addmm with scaling:
tensor([[20, 20],
        [20, 20]])
addbmm结果形状: torch.Size([4, 6])
addmv: tensor([27, 49])
addr结果:
tensor([[ 4.,  5.],
        [ 8., 10.],
        [12., 15.]])
baddbmm形状: torch.Size([10, 3, 5])


In [160]:

# 准备数据
input = torch.tensor([[10, 10], [10, 10]])  # 要加的矩阵
mat1 = torch.tensor([[1, 2], [3, 4]])        # 第一个矩阵
mat2 = torch.tensor([[5, 6], [7, 8]])        # 第二个矩阵

# 基本用法
result = torch.addmm(input, mat1, mat2)
print("addmm 结果:")
print(result)
print("\n拆解: \n", mat1.mm(mat2) + input)
# 计算: input + (mat1 @ mat2)
# mat1 @ mat2 = [[19, 22], [43, 50]]
# result = [[10+19, 10+22], [10+43, 10+50]] = [[29, 32], [53, 60]]

# 带缩放参数
result_scaled = torch.addmm(input, mat1, mat2, beta=0.9, alpha=2)
print("\n带缩放的结果:")
print(result_scaled)
# 计算: 0.5 * input + 2 * (mat1 @ mat2)
print("\nbeta: \n", 0.9 * input)
print("\nalpha: \n", 2 * mat1.mm(mat2))

print("\n拆解: \n", (2 * mat1.mm(mat2)) + (0.9 * input))

addmm 结果:
tensor([[29, 32],
        [53, 60]])

拆解: 
 tensor([[29, 32],
        [53, 60]])

带缩放的结果:
tensor([[ 38,  44],
        [ 86, 100]])

beta: 
 tensor([[9., 9.],
        [9., 9.]])

alpha: 
 tensor([[ 38,  44],
        [ 86, 100]])

拆解: 
 tensor([[ 47.,  53.],
        [ 95., 109.]])


In [161]:
result.t()

tensor([[29, 53],
        [32, 60]])

In [164]:
A = torch.tensor([[4.0, 7.0],
                  [2.0, 6.0]])

# 求逆
A_inv = torch.inverse(A)
print("原始矩阵 A:")
print(A)
print("\n逆矩阵 A⁻¹:")
print(A_inv)

原始矩阵 A:
tensor([[4., 7.],
        [2., 6.]])

逆矩阵 A⁻¹:
tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])


In [166]:
A.mm(A_inv)

tensor([[ 1.0000e+00,  2.3842e-07],
        [-1.1921e-07,  1.0000e+00]])

In [169]:
import matplotlib.pyplot as plt

# 创建一个简单的矩阵
A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]])

# 进行 SVD 分解
U, S, Vt = torch.svd(A)

print("原始矩阵 A (3×2):")
print(A)
print(f"\nU (3×3):\n{U}")
print(f"\nS (2个奇异值):\n{S}")
print(f"\nV^T (2×2):\n{Vt}")

# 重建矩阵
A_reconstructed = U[:, :2] @ torch.diag(S) @ Vt
print(f"\n重建误差: {torch.norm(A - A_reconstructed):.6f}")

原始矩阵 A (3×2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

U (3×3):
tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])

S (2个奇异值):
tensor([9.5255, 0.5143])

V^T (2×2):
tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])

重建误差: 0.000003


In [180]:
print("U:\n", U)
print("U format:\n", U[:, :2])
print("S:\n", S)
print("S format:\n", torch.diag(S))
print("Vt:\n", Vt)

A_reconstructed = U @ torch.diag(S) @ Vt
print("result:\n", A_reconstructed)

U:
 tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
U format:
 tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
S:
 tensor([9.5255, 0.5143])
S format:
 tensor([[9.5255, 0.0000],
        [0.0000, 0.5143]])
Vt:
 tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])
result:
 tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


In [182]:
x = torch.arange(1, 4).view(1, 3)
print(x)
y = torch.arange(1, 5).view(4, 1)
print(y)
print(x + y)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])


In [184]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
print(id_before)
y = y + x
print(id(y) == id_before) # False

2923187810336
False


In [185]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

True


In [186]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True


In [190]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [191]:
a += 1
print(a, b)
b += 1
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [192]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [193]:
a += 1
print(a, b)
b += 1
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [196]:
c = torch.tensor(a)
a += 1
print(a, c, x)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64) tensor([1, 2])


In [197]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
